/****************************************************************************************************************************************************\
 *** 
 *** Simulink model       : APSA
 *** TargetLink subsystem : APSA/APSA
 *** Codefile             : APSA.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2016-05-17 16:10:11
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : Standard
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Variable vector widths                   : enabled
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : enabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : disabled
 *** Exploit ranges if not erasable           : disabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : 31 chars
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : enabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : enabled
 *** Inlining Threshold                       : 6
 *** Line break limit                         : 150
 *** Target optimized boolean data type       : enabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : C:\Program Files\dSPACE TargetLink 4.0\Matlab\Tl\Config\codegen\cconfig.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLink 4.0\Matlab\Tl\XML\CodeGen\Stylesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.0 from 30-Oct-2014
 *** Code generator version  : Build Id 4.0.0.23 from 2014-10-21 15:54:50
 *** Copyright (c) 2014 dSPACE GmbH
\****************************************************************************************************************************************************/

#ifndef APSA_H
#define APSA_H

/*------------------------------------------------------------------------------------------------------------------*\
  DEFINES (OPT)
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  INCLUDES
\*------------------------------------------------------------------------------------------------------------------*/
#include "tl_defines_APSA.h"
#include "tl_basetypes.h"
/*------------------------------------------------------------------------------------------------------------------*\
  DEFINES
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  TYPEDEFS
\*------------------------------------------------------------------------------------------------------------------*/

struct BS_IP_Sa1_APSA_INPUT_DELTA {
   UInt8 DELTA_1;
   UInt8 DELTA_2;
}; /* bus inport struct */
struct BS_IP_Sa1_APSA_INPUT_Low_Level {
   Int16 Hall_Counter;
   Int16 Vbatt;
   UInt16 Current;
   UInt8 Enable_APSA;
   UInt8 Enable_Adaptation;
}; /* bus inport struct */
struct BS_IP_Sa1_APSA_INPUT_Mota {
   UInt16 Lenght_Motor_Stroke;
   UInt8 Check_Antipinch;
   UInt8 Cmd_Motor;
   UInt8 Cmd_Motor_Lift;
   UInt8 Write_Map;
}; /* bus inport struct */
struct BS_OP_Sa1_APSA_OUTPUT {
   Int16 Threshold_AntiPinch_Update;
   Int16 Threshold_Attention_Update;
   Int16 cnt_antipinch;
   UInt8 Antipinch_Active;
   UInt8 Fail_Sens_Current;
   UInt8 Index_vector;
}; /* bus outport struct */
struct tag_SIBFS_APSA_chart_a_tp {
   unsigned int Ca1_APSA_chart_ns : 3;
   unsigned int Ca17_WAIT_INRUSH_TIME_BACKWARD : 1;
   unsigned int Ca18_Antipinch_Active : 1;
   unsigned int Ca19_WAIT_ADAP__N_TIME_BACKWARD : 1;
   unsigned int Ca7_WAIT_INRUSH_TIME_FORWARD : 1;
   unsigned int Ca8_Antipinch_Active : 1;
   unsigned int Ca9_WAIT_ADAPT__ON_TIME_FORWARD : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */
struct tag_SIBFS_Average_mobile_Filter_8samp_a_tp {
   unsigned int Ca24_AVERAGE : 1;
}; /* Type of structure containing bitfields for Stateflow chart  */
/*------------------------------------------------------------------------------------------------------------------*\
  ENUMS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  VARIABLES
\*------------------------------------------------------------------------------------------------------------------*/

/********************************************************************************************************************\
   EXTERN_GLOBAL: external global variables (RAM) | Width: 16
\********************************************************************************************************************/
EXTERN_GLOBAL UInt16 EERAM_CounterVectorDownBwd[13];
EXTERN_GLOBAL UInt16 EERAM_CounterVectorDownFwd[13];
EXTERN_GLOBAL UInt16 EERAM_CounterVectorUpBwd[13];
EXTERN_GLOBAL UInt16 EERAM_CounterVectorUpFwd[13];
EXTERN_GLOBAL Int16 EERAM_Current_Map_Backward[100];
EXTERN_GLOBAL Int16 EERAM_Current_Map_Forward[100];

/********************************************************************************************************************\
   EXTERN_GLOBAL: external global variables (RAM) | Width: 8
\********************************************************************************************************************/
EXTERN_GLOBAL UInt8 EERAM_Threshold_Antipinch_Backward /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
EXTERN_GLOBAL UInt8 EERAM_Threshold_Antipinch_Forward /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
EXTERN_GLOBAL UInt8 EERAM_Threshold_Att_Backward /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;
EXTERN_GLOBAL UInt8 EERAM_Threshold_Att_Forward /* LSB: 2^0 OFF:  0 MIN/MAX:  0 .. 255 */;

/********************************************************************************************************************\
   SLGlobal: Default storage class for global variables | Width: N.A.
\********************************************************************************************************************/
extern struct BS_IP_Sa1_APSA_INPUT_DELTA APSA_INPUT_DELTA;

extern struct BS_IP_Sa1_APSA_INPUT_Low_Level APSA_INPUT_Low_Level;

extern struct BS_IP_Sa1_APSA_INPUT_Mota APSA_INPUT_Mota;

extern struct BS_OP_Sa1_APSA_OUTPUT APSA_OUTPUT;

/********************************************************************************************************************\
   SLGlobalInit: Default storage class for global variables with initial value | Width: 16
\********************************************************************************************************************/
extern Int16 Current_Read_Average;
extern Int16 Delta_Current_actual;

/*------------------------------------------------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*------------------------------------------------------------------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*------------------------------------------------------------------------------------------------------------------*/
/********************************************************************************************************************\
   GlobalStep: Default function class for not static model step functions
\********************************************************************************************************************/
extern void APSA(void);


#endif /* APSA_H */
/*------------------------------------------------------------------------------------------------------------------*\
  END OF FILE
\*------------------------------------------------------------------------------------------------------------------*/
