/**
 * @file DISPA_cbk.h
 * @brief DISPA Module: callback function definition
 *                      The callback defined here are used for DISPA input update
 *
 * @version 0.1
 * @author Davide Fogliano (Polimatica S.r.l.)
 * @date 24 june 2015
 * @note (C) Copyright 2014 Bitron S.p.A. @link www.Bitron.net
 */
/*
|-----------------------------------------------------------------------------
|               A U T H O R   I D E N T I T Y
|-----------------------------------------------------------------------------
| Initials     Name                      Company
| --------     ---------------------     -------------------------------------
| DF           Davide Fogliano           Polimatica S.r.l
|-----------------------------------------------------------------------------
| DC           Daniele Cloralio          Ema S.r.l
|-----------------------------------------------------------------------------
|               R E V I S I O N   H I S T O R Y
|-----------------------------------------------------------------------------
| Date       Ver  Author  Description
| ---------  ---  ------  ----------------------------------------------------
| 24/06/15   0.1  DF      First draft
|-----------------------------------------------------------------------------
| 24/07/15   0.2  DC      Porting to 952 project
|-----------------------------------------------------------------------------
*/

#ifndef __DISPA_CBK_H__
#define __DISPA_CBK_H__

#ifdef DISPA_IF_OWNER
	#define DISPA_EXTERN
#else
	#define DISPA_EXTERN		extern
#endif

/*______ I N C L U D E - F I L E S ___________________________________________*/

/*______ G L O B A L - T Y P E S _____________________________________________*/

/*______ G L O B A L - D E F I N E S _________________________________________*/

/*______ G L O B A L - D A T A _______________________________________________*/

/*______ P R I V A T E - M A C R O S _________________________________________*/

/*______ G L O B A L - M A C R O S ___________________________________________*/

/*______ G L O B A L - F U N C T I O N S - P R O T O T Y P E S _______________*/

/**
 * @brief Callback routine generated by button press event
 * @author Mastrodonato Matteo - Bitron S.p.A.
 * @param [in]
 * @param [out]
 * @return None
 */
DISPA_EXTERN void DISPA_SlideFwInput_Cbk(void);
DISPA_EXTERN void DISPA_SlideBwInput_Cbk(void);
DISPA_EXTERN void DISPA_BackrestFwInput_Cbk(void);
DISPA_EXTERN void DISPA_BackrestBwInput_Cbk(void);
DISPA_EXTERN void DISPA_TiltUpInput_Cbk(void);
DISPA_EXTERN void DISPA_TiltDwInput_Cbk(void);
DISPA_EXTERN void DISPA_LiftUpInput_Cbk(void);
DISPA_EXTERN void DISPA_LiftDwInput_Cbk(void);
DISPA_EXTERN void DISPA_Mem1Input_Cbk(void);
DISPA_EXTERN void DISPA_Mem2Input_Cbk(void);
DISPA_EXTERN void DISPA_Mem3Input_Cbk(void);
DISPA_EXTERN void DISPA_BackrLiftOpen_Cbk(void);
DISPA_EXTERN void DISPA_SlideTiltOpen_Cbk(void);
DISPA_EXTERN void DISPA_MemOpen_Cbk(void);
/**
 * @brief Callback routine generated by timers expiring event
 * @author Mastrodonato Matteo - Bitron S.p.A.
 * @param [in]
 * @param [out]
 * @return None
 */
DISPA_EXTERN void DISPA_ClrRecallReq(void);
DISPA_EXTERN void DISPA_UserSavePos(void);
/**
 * @brief Callback routine generated by CAN message received
 * @author Mastrodonato Matteo - Bitron S.p.A.
 * @param [in]
 * @param [out]
 * @return None
 */
DISPA_EXTERN void DISPA_StatusClimateCbk(void);
DISPA_EXTERN void DISPA_StatusLinCbk(void);

/**
 * @brief Changes the "Driver Door" status only in CountryCode equal to USA OR CANADA OR MEXICO
 * @author Fabio Zanchetta
 * @param [in] new Driver Door Status
 * @param [out] None
 * @return None
 */
extern void  DISPA_DriverDoorStsChanged(CMMD_DoorSts_t DriverDoorStatus);

/**
 * @brief Callback routine generated by CAN message received
 * @author Fabio Zanchetta - Bitron S.p.A.
 * @param [in]
 * @param [out]
 * @return None
 */
DISPA_EXTERN void DISPA_GateWayRemoteCranking(void);

/*______ E X T E R N A L - D A T A ___________________________________________*/


#endif /* end __DISPA_CBK_H */
